apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc
spec:
  storageClassName: "ebs-sc" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-dynamic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic-pod
  labels:
    purpose: dynamicvol
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f    
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-dynamic
    persistentVolumeClaim:
      claimName: ebs-dynamic-pvc
---
apiVersion: v1 
kind: Service
metadata: 
  name: nginx-dynamic-pv
spec:
  type: LoadBalancer
  selector: 
     purpose: dynamicvol
  ports:
    - name: vol-svc
      protocol: TCP
      port: 80
      targetPort: 80
