apiVersion: v1
kind: Pod
metadata:
  namespace: expense
  name: resorces
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
      requests:
        cpu: 100m
        memory: 68Mi
      limits:
        cpu: 120m
        memory: 68Mi


