apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    project: expense
    env: dev
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec:
  selector:
    project: expense
    env: dev
    app: nginx
  ports:
    - name: nginx-svc-port
      protocal: TCP
      port: 80
      targetport: 80

