apiVersion: v1
kind: Pod
metadata: 
  name: pod-nodeport
  labels:
    project: exp
    env: dev
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: node-port-svc
  selector:
    project: exp
    env: dev
    app: nginx
spec:
  type: NodePort 
  selector:
    project: exp
    env: dev
    app: nginx
  ports:
    - name: nginx-node
      protocol: TCP
      port: 80
      targetPort: 80




    
