apiVersion: v1
kind: Pod
metadata:
  name: pod-loadbalancer
  labels:
    project: exp
    env: dev
    app: alb
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: nginx-configmap
---
apiVersion: v1
kind: Pod
metadata: 
  name: pod-svc-alb
spec:
  type: LoadBalancer
  selector:
    project: exp
    env: dev
    app: alb
  ports:
    - name: nginx-alb
      protocol: TCP
      port: 80
      targetPort: 80
