apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: nginx-replicaset
  labels:
    app: nginx1
    tier: fronend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: fronend
  template:
    metadata:
      labels:
        app: nginx
        tier: fronend
    spec:
      containers:
        - name: nginx
          image: nginx  
---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-replica-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx1
    tier: fronend1
  ports: 
    - name: nginx-svc-rep
      protocol: TCP
      port: 80
      targetPort: 80
