apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: nginx-replicaset
  labels:
    app: nginx1
    tier: fronend1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: fronend
  template:
    metadata:
      labels:
        app: nginx
        tier: fronend
    spec:
      containers:
        - name: nginx
          image: nginx  