apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-deploy
  labels:
    project: expense
    env: dev
    tier: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense
      tier: mysql
  template:
    metadata:
      labels:
        app: expense
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: sankarjuvva/mysql:latest
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
spec:
  selector:
    project: expense
    env: dev
    tier: mysql
  ports:
    - name: mysql-svc
      protocol: TCP 
      port: 3306
      targetPort: 3306

  
