apiVersion: v1 
kind: ConfigMap
metadata:
  name: backend
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
      app: expense
      env: dev
      tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense
      env: dev
      tier: backend
  template:
    metadata:
      labels:
        app: expense
        env: dev
        tier: backend
    spec:
      containers:
        - name: exp-backend
          image: sankarjuvva/backend:latest
          resources:
          requests:
            cpu: 100m
            memory: 128Mi
   #limits should increase
          limits:
            cpu: 110m
            memory: 130Mi
          envFrom:
            - configMapRef:
                name: backend
---
apiVersion: v1 
kind: Service
metadata:
 name: backend-svc
spec:
  selector: 
    app: expense
    tier: backend
  ports:
    - name: backend-port
      protocol: TCP
      port: 8080
      targetPort: 8080

