# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    app: mysql
    tier: db
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
    tier: db
---
# Normal service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: db
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db
  serviceName: mysql-headless
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: sankardevops/mysql:latest
      volumeMounts:
        - name: mysql-vol-claim
          path: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-vol-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 2Gi
